# Generated by Django 5.0.3 on 2024-03-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeautySalonapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='additional_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='details',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
